// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlfjrdntkcomrroeuvfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsZmpyZG50a2NvbXJyb2V1dmZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NDcxMjIsImV4cCI6MjA3MzQyMzEyMn0.cBoK4-3rARquKPsT1ov5w5dvkMQnK4HKleoIw9p9zaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});